#!/usr/bin/env bash

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
for i in {0..7}; do
    printf -v fbright$i %b "\e[9${i}m"
done
bld=$'\e[1m'
rst=$'\e[0m'
inv=$'\e[7m'

cat << EOF
$bld
 $fbright3 ▄      $rst$f1      ▄▄      $fbright2      ▄▄      $fbright4      ▄▄      $fbright5      ▄▄      $fbright6      ▄▄     
 $fbright3 ███▄▄  $f1   ██▬██▬██   $fbright2   ██▬██▬██   $fbright4   ██▬██▬██   $fbright5   ██▬██▬██   $fbright6   ██▬██▬██  
 $fbright3 █████▀▀$f1     ████     $fbright2     ████     $fbright4     ████     $fbright5     ████     $fbright6     ████    
 $fbright3 █▀▀    $f1   ▄██  ██▄   $fbright2   ▄██  ██▄   $fbright4   ▄██  ██▄   $fbright5   ▄██  ██▄   $fbright6   ▄██  ██▄  
 $fbright3 █      $f1 ▄▄▄▀█  █▀▄▄▄ $fbright2 ▄▄▄▀█  █▀▄▄▄ $fbright4 ▄▄▄▀█  █▀▄▄▄ $fbright5 ▄▄▄▀█  █▀▄▄▄ $fbright6 ▄▄▄▀█  █▀▄▄▄
 $fbright3▄█▄     $f1 ███▀████▀███ $fbright2 ███▀████▀███ $fbright4 ███▀████▀███ $fbright5 ███▀████▀███ $fbright6 ███▀████▀███
            $f1  ▀  ▀        $fbright2  ▀  ▀        $fbright4  ▀  ▀        $fbright5  ▀  ▀        $fbright6  ▀  ▀     
$rst  




EOF
